# Generated by Django 5.1.6 on 2025-05-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('supplier', 'supplier'), ('customer', 'customer'), ('delivery', 'delivery')], default='customer', max_length=20),
        ),
    ]
